# This workflow builds all the NodeJS projects using a reusable build workflow.

name: Build

on:
  push:
    branches:
      - main
      - release/*
      - instance/*
  pull_request:
    branches:
      - main
      - release/*
      - instance/*

jobs:
#   build-backend:
#     name: backend
#     uses: Hack-Team-One/accessible-learning-ai/.github/workflows/build-project.yml@main
#     with:
#       project: backend
  build-interface:
    name: interface
    uses: Hack-Team-One/accessible-learning-ai/.github/workflows/build-project.yml@main
    with:
      project: interface
