# This workflow will do a clean install of node dependencies, cache/restore them, build the source code
# and run tests across different versions of node
# For more information, see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build project

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  check:
    name: Build `${{ inputs.project }}`
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.project }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.project }}

      - name: Build the project
        run: npm run build
        env:
          NODE_ENV: test
          # NODE_OPTIONS: '--max_old_space_size=4096' // Used to increase the memory limit
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        working-directory: ${{ inputs.project }}

      # - name: Test the project
      #   run: npm test
      #   working-directory: ${{ inputs.project }}
